// <auto-generated />
using System;
using Alice_Timetable.Engine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alice_Timetable.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200510164704_DeleteEmployee")]
    partial class DeleteEmployee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alice_Timetable.Models.BsuirScheduleResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("currentWeekNumber")
                        .HasColumnType("int");

                    b.Property<string>("dateEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sessionEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sessionStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studentGroupid")
                        .HasColumnType("int");

                    b.Property<string>("todayDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tomorrowDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("studentGroupid");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Alice_Timetable.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("academicDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calendarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rank")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Alice_Timetable.Models.ExamSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BsuirScheduleResponseId")
                        .HasColumnType("int");

                    b.Property<string>("weekDay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BsuirScheduleResponseId");

                    b.ToTable("ExamSchedule");
                });

            modelBuilder.Entity("Alice_Timetable.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BsuirScheduleResponseId")
                        .HasColumnType("int");

                    b.Property<string>("weekDay")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BsuirScheduleResponseId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Alice_Timetable.Models.Schedules.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BsuirScheduleResponseId")
                        .HasColumnType("int");

                    b.Property<int?>("BsuirScheduleResponseId1")
                        .HasColumnType("int");

                    b.Property<int?>("ExamScheduleId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("auditory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endLessonTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gradebookLesson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gradebookLessonlist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lessonTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lessonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numSubgroup")
                        .HasColumnType("int");

                    b.Property<string>("startLessonTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentGroupInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentGroupModelList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weekNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("zaoch")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BsuirScheduleResponseId");

                    b.HasIndex("BsuirScheduleResponseId1");

                    b.HasIndex("ExamScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Schedule1");
                });

            modelBuilder.Entity("Alice_Timetable.Models.StudentGroup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("calendarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("course")
                        .HasColumnType("int");

                    b.Property<int>("facultyId")
                        .HasColumnType("int");

                    b.Property<string>("facultyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("specialityDepartmentEducationFormId")
                        .HasColumnType("int");

                    b.Property<string>("specialityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("StudentGroup");
                });

            modelBuilder.Entity("Alice_Timetable.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Alice_Timetable.Models.BsuirScheduleResponse", b =>
                {
                    b.HasOne("Alice_Timetable.Models.StudentGroup", "studentGroup")
                        .WithMany()
                        .HasForeignKey("studentGroupid");
                });

            modelBuilder.Entity("Alice_Timetable.Models.Employee", b =>
                {
                    b.HasOne("Alice_Timetable.Models.Schedules.Schedule", null)
                        .WithMany("employee")
                        .HasForeignKey("ScheduleId");
                });

            modelBuilder.Entity("Alice_Timetable.Models.ExamSchedule", b =>
                {
                    b.HasOne("Alice_Timetable.Models.BsuirScheduleResponse", null)
                        .WithMany("examSchedules")
                        .HasForeignKey("BsuirScheduleResponseId");
                });

            modelBuilder.Entity("Alice_Timetable.Models.Schedule", b =>
                {
                    b.HasOne("Alice_Timetable.Models.BsuirScheduleResponse", null)
                        .WithMany("schedules")
                        .HasForeignKey("BsuirScheduleResponseId");
                });

            modelBuilder.Entity("Alice_Timetable.Models.Schedules.Schedule", b =>
                {
                    b.HasOne("Alice_Timetable.Models.BsuirScheduleResponse", null)
                        .WithMany("todaySchedules")
                        .HasForeignKey("BsuirScheduleResponseId");

                    b.HasOne("Alice_Timetable.Models.BsuirScheduleResponse", null)
                        .WithMany("tomorrowSchedules")
                        .HasForeignKey("BsuirScheduleResponseId1");

                    b.HasOne("Alice_Timetable.Models.ExamSchedule", null)
                        .WithMany("schedule")
                        .HasForeignKey("ExamScheduleId");

                    b.HasOne("Alice_Timetable.Models.Schedule", null)
                        .WithMany("schedule")
                        .HasForeignKey("ScheduleId");
                });
#pragma warning restore 612, 618
        }
    }
}
